<?php

namespace App\Http\Livewire\Reports;

use App\Models\BranchesModel;
use App\Models\LoansModel;
use Illuminate\Support\Facades\DB;
use Livewire\Component;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class GeneralLoanReport extends LivewireDatatable
{

    public $exportable=true;
    public $branchId;


    protected $listeners=['changeBranch'=>'updateBranch'];



    public function updateBranch($id){
        $this->branchId=$id;

    }





    public function builder()
    {
        $query=LoansModel::query();
        if($this->branchId){
            $query->where('branch_id',$this->branchId);
        }




  return $query;
    }



    public function columns()
    {
        return [
            column::name('created_at')->label('date'),
            column::name('loan_id')->label('id'),
            column::name('loan_account_number')->label('account number'),
            column::name('client_number')->label('client number'),
            column::callback('loan_sub_product',function($sub_product_id){
                return DB::table('loan_sub_products')->where('sub_product_id',$sub_product_id)->value('sub_product_name');
            })->label('product name'),
            column::name('guarantor')->label('guarantor'),
            column::callback('branch_id',function($branch_id){
                return BranchesModel::where('id',$branch_id)->value('name');
            })->label('branch'),
            column::callback('principle',function($principle){
                return number_format($principle);
            })->label('principle')->searchable(),
            Column::callback(['days_in_arrears'],function($days_in_arrears){
                if($days_in_arrears >0){
                    return '<div class="bg-red-500 p-2 "> '.$days_in_arrears.' </div>';
                }else{
                    return '<div class="bg-green-500 p-2 "> 0 </div>';
                }
            })->label('past due date(days)')->searchable(),

            column::callback('interest',function ($interest){
                return $interest.'%';
            })->label('interest')->searchable(),
            column::name('business_name')->label('business name'),
            column::name('heath')->label('health'),
            column::name('tenure')->label('tenure'),
            column::name('status')->label('status')


        ];

        // TODO: Change the autogenerated stub
    }
}
