<?php

namespace App\Http\Livewire\Procurement;

use App\Models\Employee;
use App\Models\PurchaseRequisition;
use App\Models\Vendor;
use Livewire\Component;
use App\Models\VendorSubmission;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class POView extends LivewireDatatable
{

    public function builder()
    {
        return  VendorSubmission::query();// TODO: Change the autogenerated stub
    }

    public function columns():array
    {

        return [
            Column::name('id')->label('id'),
            Column::callback('vendorId', function ($vendorId){
                return Vendor::where('id',$vendorId)->value('organization_name');
            })->label('vendor  Id'),
            Column::callback('requestId', function ($requestId){
                return  PurchaseRequisition::where('id',$requestId)->value('requisition_description');
            })->label('purchase descriptions'),
            Column::name('endDate')->label('end Date'),
            Column::name('invoice')->label('invoice'),
            Column::name('descriptions')->label('descriptions'),
            Column::name('updated_at')->label('submission date'),
        ];
    }

}
